= Bandit 8 Writeup
Miguel Magana <m1k3.0xd@gmail.com>
v1.0, 2022-06-07
:toc: auto

This is a writeup for the Over the Wire Bandit wargame. This writeup will guide you through each level to teach CTF/Wargame basics.

WARNING: DO NOT SHARE THE FLAG ONCE FOUND

== Objective
The *bandit8* password is stored in a text file call *data.txt* next to the word millionth.

== Get the Flag
The file is not hidden. *ls* the current directory and you will find the *data.txt* file in the home directory. *cat* this file and you get tons of flags. This output has to be filtered and passed to *grep* with triggers to find the flag next to the word *millionth*.

This wargame introduces you to *grep*. In order to find the correct line in all of the flags you:

 cat data.txt | grep "millionth"

This pipes the output of *cat* into *grep* and searches for the lines that contain the word *_millionth_*. There will be only one line with *_millionth_*.

Copy your flag and create your password file then change your command to get into the next level.