= Bandit 2 Writeup
Miguel Magana <m1k3.0xd@gmail.com>
v1.0, 2022-06-07
:toc: auto

This is a writeup for the Over the Wire Bandit wargame. This writeup will guide you through each level to teach CTF/Wargame basics.

WARNING: DO NOT SHARE THE FLAG ONCE FOUND

== Objective
*bandit2* tests your skills in navigating the file system and locating a file with a dash in the name. Googling the "finding a file starting with a dash" will be a helpful search and will provide the answer.

== Get the Flag
In order to view the dashed file name you need to use the relative path:

 ./- 

If you do not use the relative path using the *_cat_ -* is recognized as another command and not a file which takes you straight into *_stdin_*. Your command prompt will change and will accept any input that is input into the keyboard. You have to break the process and type in the relative path.

 cat ./-

This will echo the next flag. Copy it into your next file and change your *sshpass* command to get into the next level.