= Bandit 31 Writeup
:author: Miguel Magana
:email:  m1k3.0xd@gmail.com
:revnumber: v1.0 
:revdate: 2022-06-07
:revremark: First draft
:toc: auto


This is a writeup for the Over the Wire Bandit wargame. This writeup will guide you through each level to teach CTF/Wargame basics.

WARNING: DO NOT SHARE THE FLAG ONCE FOUND

== The Objective
There is a git repository at *ssh://bandit30-git@localhost/home/bandit30-git/repo*. The password for the user *bandit30-git* is the same as for the user *bandit30*.

Clone the repository and find the password for the next level.

== Get the Flag
Navigating through a repo using git to find the flag in old branches and commits. First create your working directory.

 mkdir /tmp/m1k3
 cd /tmp/m1k3

 cat /etc/bandit_pass/bandit30

 git clone ssh://bandit30-git@localhost/home/bandit30-git/repo

 cd repo/

 git log

The logs did not produce anything useful. There are only 2 branches. Checkout the next branch and *git log* to see the commits. Checking out both branches doesn't produce much from the inital commits.

There is still more information in the *.git* directory. For this level the interesting file is *packed-refs*.

 cat packed-refs

This shows some additional commits. *git show* the one with *secret* in the name and will spit out another hash which is the flag for the next level. Create your password file and change your command to get into the next level.