= Bandit 28 Writeup
:author: Miguel Magana
:email:  m1k3.0xd@gmail.com
:revnumber: v1.0 
:revdate: 2022-06-07
:revremark: First draft
:toc: auto


This is a writeup for the Over the Wire Bandit wargame. This writeup will guide you through each level to teach CTF/Wargame basics.

WARNING: DO NOT SHARE THE FLAG ONCE FOUND

== The Objective
There is a git repository at *ssh://bandit27-git@localhost/home/bandit27-git/repo*. The password for the user *bandit27-git* is the same as for the user *bandit27*.

Clone the repository and find the password for the next level.

== Get the Flag
To get the flag for *bandit28* you have to clone the repo into a directory that you have read / write access. For this you an make a temporary folder.

 mkdir /tmp/m1k3
 cd /tmp/m1k3
 
 cat /etc/bandit_pass/bandit27

TIP: The last command is to have the password ready to paste into the next step

*git clone* and the rest of the repo address in this directory will clone the repo.

 git clone ssh://bandit27-git@localhost/home/bandit27-git/repo

Follow the prompts when asked for the password. Paste the password for *bandit27* and let Git clone the repo. Change into the directory and *cat* the README file. Create your password file and change your command to get into the next level.